services:
  site-nginx:
    image: nginx:alpine
    container_name: site-nginx
    ports:
      - "8002:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    depends_on:
      - site-php
    networks:
      - net

  site-php:
    build:
      args:
        user: mateus
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: site-php
    container_name: site-php
    volumes:
      - .:/var/www
    networks:
      - net

  site-pgsql:
    image: postgres:17
    container_name: site-pgsql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
    networks:
      - net

networks:
  net:
    driver: bridge
